### ISSUE TITLE
Extra button on first screen

### ISSUE THREAD

**Issue by siddharthvp** [Ankit-Gupta18/Edit-Request-Wizard#8]
Just a single button is needed which does verification and leads user to next screen.

<img width="506" alt="Screenshot 2022-07-30 at 11 56 43 PM" src="https://user-images.githubusercontent.com/31818903/181936719-59f46983-7a1c-4ddd-86d0-c58a9e12e4cd.png">

Two buttons makes the UX poorer as you can change the URL and click "Next" without hitting "Verify" (shown above).

Or the other way round:

<img width="588" alt="Screenshot 2022-07-30 at 5 42 35 PM" src="https://user-images.githubusercontent.com/31818903/181936749-0a80457a-8a4a-4743-898f-18fb97f1e845.png">

**Comment by enterprisey** [comment]
the concern with a single button was if the source is borderline, the user should have to "confirm" that. I guess we don't have to support that, because borderline sources are a judgment call that the user isn't equipped to make. although, actually, maybe we want something like "if you can use a different source for this, do so?" but do we make that a hard restriction (so, we'd get rid of the "borderline" category)?

**Comment by siddharthvp** [comment]
hmm, I see. In that case I think #6 solves the problem in the better way. FWIW I think borderline sources should not be hard disallowed.
